export const CTEZ_ADDRESS = process.env.REACT_APP_LEGACY_CTEZ_CONTRACT;
export const CTEZ_CONTRACT_BIGMAP = process.env.REACT_APP_LEGACY_CTEZ_CONTRACT_BIGMAP ?? '30161';
export const CTEZ_FA12_ADDRESS = process.env.REACT_APP_LEGACY_CTEZ_FA12_CONTRACT;
export const CFMM_ADDRESS = process.env.REACT_APP_LEGACY_CFMM_CONTRACT;
export const LQT_FA12_ADDRESS = process.env.REACT_APP_LEGACY_LQT_FA12_CONTRACT;

export const CONTRACT_DEPLOYMENT_DATE = process.env.REACT_APP_LEGACY_CONTRACT_DEPLOYMENT_DATE || '';

export const TOTAL_OVEN_IMAGES = 11;
